"""
Writes a complete, human-readable, secrets-free record of each tenant into
its own file in the GitOps repo (settings.git_tenant_info_dir, default
"tenant-info/{slug}.yaml") -- separate from, and never read by, the Helm
values.yaml Argo CD actually deploys from (settings.git_tenants_dir).

Source of truth is still the PostgreSQL `tenants` table; this is a mirror of
it written on every create/update/delete so a human (or any tool without
Postgres access) can see a tenant's full record -- placement, subscription
tier, status, timestamps -- from the git repo alone. Contains no secrets:
everything here is already non-sensitive metadata that also lives in the
committed values.yaml or the DB row itself.
"""
import yaml

from app.models.tenant import Tenant
from app.services.cluster_selector import ClusterInfo

_HEADER = (
    "# Generated by tenant-operator. Do not edit by hand -- changes will be\n"
    "# overwritten on the next tenant create/update. Source of truth: the\n"
    "# PostgreSQL `tenants` table. Contains no secrets -- see Vault for those.\n"
    "\n"
)


def _iso(dt) -> str | None:
    return dt.isoformat() if dt is not None else None


def render_tenant_info_yaml(tenant: Tenant, cluster: ClusterInfo) -> str:
    data = {
        "tenantId": tenant.slug,
        "tenantSeq": tenant.tenant_seq,
        "tenantName": tenant.tenant_name,
        "displayName": tenant.display_name,
        "email": tenant.email,
        "domain": tenant.domain,
        "tier": tenant.tier,
        "environment": tenant.environment,
        "appType": tenant.app_type,
        "placement": {
            "spoke": cluster.name,
            "region": cluster.region,
            "namespace": tenant.namespace,
            "argocdClusterServer": cluster.argocd_cluster_server,
        },
        "sizing": {
            "users": tenant.users,
            "databaseSize": tenant.database_size,
        },
        "disabledServices": tenant.disabled_services or [],
        "status": tenant.status.value if tenant.status else None,
        "gitCommit": tenant.git_commit,
        "helmChartVersion": tenant.helm_chart_version,
        "hubCr": {
            "name": tenant.hub_cr_name,
            "uid": tenant.hub_cr_uid,
        },
        "createdBy": tenant.created_by,
        "createdAt": _iso(tenant.created_at),
        "updatedAt": _iso(tenant.updated_at),
        "deletedAt": _iso(tenant.deleted_at),
    }
    return _HEADER + yaml.safe_dump(data, sort_keys=False, default_flow_style=False)
