apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant.id }}
  namespace: {{ .Values.tenant.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.tenant.id }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Values.tenant.id }}
  ports:
    - port: 80
      targetPort: 80
