{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tenant-operator.fullname" . }}-git-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled (not .Values.postgresql.persistence.existingClaimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tenant-operator.postgresFullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes: ["ReadWriteOnce"]
{{- if .Values.postgresql.persistence.storageClassName }}
  storageClassName: {{ .Values.postgresql.persistence.storageClassName }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
