{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant-operator.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
